### ISSUE TITLE
Built in reparametrization trick

### ISSUE THREAD

**Issue by ferrine** [stepelu/ptstat#1]
Just an idea to support stochastic gradients trough samples

**Comment by stepelu** [comment]
It is already the case for continuous random variables, I'll try when possible to keep implementing `sample()` in a way that gives you the pathwise derivative estimator (i.e. reparametrization trick) for free.

For discrete random variables approximations are possible, such as the gumbel-max trick for which contributions are welcome.

**Comment by stepelu** [comment]
Closing for now, thanks for the remark.
